[project]
name = "mvanet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shunsuke KITADA", email = "shunsuke.kitada.0831@gmail.com" },
]
requires-python = ">=3.11"
dependencies = [
    "einops>=0.8.1",
    "timm>=1.0.22",
    "torch>=2.0.0",
    "torchvision>=0.15.0",
    "transformers[torch,torch-vision]>=4.57.3",
    "ttach>=0.0.3",
]

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["mypy>=1.0.0", "pytest>=6.0.0", "ruff>=0.1.5", "scipy-stubs>=1.17.0.0"]
original = ["mvanet-original"]

[tool.uv.sources]
mvanet-original = { path = "./mvanet_original" }

[tool.ruff.lint]
ignore = [
    "E741", # ambiguous variable name
]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
exclude = "^tests/"
